import Link from 'next/link'
import { redirect } from 'next/navigation'
import { AppShell } from '@/components/app-shell'
import { createClient } from '@/lib/supabase/server'

export const dynamic='force-dynamic'
type Row={branch_id:string;business_date:string;product_name:string;sales_qty:number;unit_value:number|null;closing_qty:number;closing_value:number|null}
function n(v:unknown){return Number(v??0)}
function num(v:number,d=2){return new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(v)}
function money(v:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'EGP',maximumFractionDigits:0}).format(v)}
export default async function ProductMatrix({searchParams}:{searchParams:Promise<{from?:string;to?:string}>}){
 const f=await searchParams,from=f.from??'2026-09-01',to=f.to??'2026-09-30'; const supabase=await createClient(); const {data:auth}=await supabase.auth.getClaims(); if(!auth?.claims?.sub)redirect('/login')
 const [{data},{data:branchesData},{data:warehouseData}]=await Promise.all([supabase.from('inventory_daily').select('branch_id,business_date,product_name,sales_qty,unit_value,closing_qty,closing_value').gte('business_date',from).lte('business_date',to).order('business_date'),supabase.from('branches').select('id,name').eq('is_active',true).order('name'),supabase.from('warehouse_daily_summary').select('sales_qty,sales_value,closing_qty,closing_value').gte('business_date',from).lte('business_date',to)])
 const rows=(data??[]) as Row[];const branches=(branchesData??[]) as {id:string;name:string}[]
 type Cell={salesQty:number;salesValue:number;closingQty:number;closingValue:number;last:string}; const matrix=new Map<string,Map<string,Cell>>()
 for(const x of rows){const pr=matrix.get(x.product_name)??new Map<string,Cell>();const c=pr.get(x.branch_id)??{salesQty:0,salesValue:0,closingQty:0,closingValue:0,last:''};c.salesQty+=n(x.sales_qty);c.salesValue+=n(x.sales_qty)*n(x.unit_value);if(x.business_date>=c.last){c.last=x.business_date;c.closingQty=n(x.closing_qty);c.closingValue=n(x.closing_value)};pr.set(x.branch_id,c);matrix.set(x.product_name,pr)}
 const hasProductDetail=rows.length>0;const warehouse=(warehouseData??[]) as {sales_qty:number;sales_value:number;closing_qty:number;closing_value:number}[];const aggregate={salesQty:warehouse.reduce((s,r)=>s+n(r.sales_qty),0),salesValue:warehouse.reduce((s,r)=>s+n(r.sales_value),0),closingQty:warehouse.at(-1)?n(warehouse.at(-1)?.closing_qty):0,closingValue:warehouse.at(-1)?n(warehouse.at(-1)?.closing_value):0};return <AppShell title="مصفوفة الأصناف والفروع" subtitle="مبيعات كمية/قيمة ورصيد مخزون لكل صنف عبر الفروع">
  <form className="card filters" method="get"><div className="field"><label>من</label><input type="date" name="from" defaultValue={from}/></div><div className="field"><label>إلى</label><input type="date" name="to" defaultValue={to}/></div><div className="field filter-action"><label>&nbsp;</label><button className="btn">تطبيق</button></div></form>
  <section className="card"><div className="section-head"><h2>Product Sales & Stock Matrix</h2><span className="muted">القيمة = كمية البيع × قيمة الوحدة المسجلة بالمخزون</span></div>{!hasProductDetail&&<div className="notice">تفاصيل الأصناف لم تُستورد بعد لهذا الشيت المعتمد. المتاح حاليًا إجمالي المخزون فقط: بيع {num(aggregate.salesQty)} / {money(aggregate.salesValue)} — رصيد {num(aggregate.closingQty)} / {money(aggregate.closingValue)}.</div>}<div className="table-wrap"><table><thead><tr><th>الصنف</th>{branches.map(b=><th key={b.id}>{b.name}<div className="muted">بيع / رصيد</div></th>)}<th>إجمالي البيع</th><th>إجمالي الرصيد</th></tr></thead><tbody>{[...matrix.entries()].sort((a,b)=>a[0].localeCompare(b[0],'ar')).map(([product,cells])=>{let tq=0,tv=0,sq=0;for(const c of cells.values()){tq+=c.salesQty;tv+=c.salesValue;sq+=c.closingQty}return <tr key={product}><td><Link className="row-link" href={`/inventory-movement?from=${from}&to=${to}`}>{product}</Link></td>{branches.map(b=>{const c=cells.get(b.id);return <td key={b.id}>{num(c?.salesQty??0)} / {money(c?.salesValue??0)}<div className="muted">رصيد {num(c?.closingQty??0)}</div></td>})}<td>{num(tq)} / {money(tv)}</td><td>{num(sq)}</td></tr>})}</tbody></table></div></section>
 </AppShell>
}