import {FormEvent,useEffect,useMemo,useState} from 'react'
import type {Branch} from '../domain/types'
import {getTreasury,updateCashEntry,type CashRow} from '../data/treasury'
import {DataTable} from '../components/DataTable'
const money=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n)
export function Treasury({from,to,branchId,branches,isAdmin=false}:{from:string;to:string;branchId?:string;branches:Branch[];isAdmin?:boolean}){
 const [rows,setRows]=useState<CashRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[edit,setEdit]=useState<CashRow|null>(null),[msg,setMsg]=useState('')
 const load=()=>{setLoading(true);return getTreasury({from,to,branchId}).then(setRows).catch(e=>setError(e.message||String(e))).finally(()=>setLoading(false))}
 useEffect(()=>{void load()},[from,to,branchId])
 const map=useMemo(()=>new Map(branches.map(b=>[b.id,b.name])),[branches])
 const incoming=rows.filter(r=>r.direction==='in').reduce((s,r)=>s+Number(r.amount||0),0),outgoing=rows.filter(r=>r.direction==='out').reduce((s,r)=>s+Number(r.amount||0),0)
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!edit)return;const f=new FormData(e.currentTarget);try{setMsg('جاري الحفظ…');await updateCashEntry({id:edit.id,source_code:String(f.get('source_code')||''),entry_date:String(f.get('entry_date')||''),description:String(f.get('description')||''),category:String(f.get('category')||''),inbound:Number(f.get('inbound')||0),outbound:Number(f.get('outbound')||0),running_balance:String(f.get('running_balance')||''),reason:String(f.get('reason')||'')});setEdit(null);setMsg('');await load()}catch(x:any){setMsg(x.message||String(x))}}
 if(loading)return <div className="panel loading">جاري تحميل الخزينة…</div>
 return <div>{error&&<div className="error-box">{error}</div>}<div className="kpi-grid"><article className="kpi-card"><span>الوارد</span><strong>{money(incoming)}</strong></article><article className="kpi-card"><span>الصادر</span><strong>{money(outgoing)}</strong></article><article className="kpi-card"><span>صافي الحركة</span><strong>{money(incoming-outgoing)}</strong></article></div><DataTable title="حركات الخزينة" rows={rows.map(r=>({...r,branch:map.get(r.branch_id)||'—',inbound:r.direction==='in'?r.amount:0,outbound:r.direction==='out'?r.amount:0}))} columns={[{key:'entry_date',label:'التاريخ'},{key:'branch',label:'الفرع'},{key:'source_code',label:'الكود'},{key:'description',label:'البيان'},{key:'category',label:'التصنيف'},{key:'inbound',label:'وارد',numeric:true,render:r=>money(r.inbound)},{key:'outbound',label:'صادر',numeric:true,render:r=>money(r.outbound)},{key:'running_balance',label:'الرصيد',numeric:true,render:r=>r.running_balance==null?'—':money(r.running_balance)},{key:'action',label:'إجراء',filter:false,render:r=>isAdmin?<button className="small-btn" onClick={()=>setEdit(r)}>تعديل</button>:'—'}]}/>
 {edit&&<div className="modal-backdrop"><form className="modal-card" onSubmit={save}><div className="modal-head"><h3>تعديل حركة الخزينة #{edit.id}</h3><button type="button" className="small-btn" onClick={()=>setEdit(null)}>إغلاق</button></div><div className="form-grid"><label>الكود<input name="source_code" defaultValue={edit.source_code||''}/></label><label>التاريخ<input name="entry_date" type="date" defaultValue={edit.entry_date} required/></label><label>البيان<input name="description" defaultValue={edit.description||''}/></label><label>التصنيف<input name="category" defaultValue={edit.category||''}/></label><label>الوارد<input name="inbound" type="number" min="0" step="0.01" defaultValue={edit.direction==='in'?Number(edit.amount||0):0}/></label><label>الصادر<input name="outbound" type="number" min="0" step="0.01" defaultValue={edit.direction==='out'?Number(edit.amount||0):0}/></label><label>رصيد آخر<input name="running_balance" type="number" step="0.01" defaultValue={edit.running_balance??''}/></label><label className="full">سبب التعديل<textarea name="reason" rows={3} required placeholder="سبب التعديل"></textarea></label></div>{msg&&<p className="muted">{msg}</p>}<button className="primary">حفظ التعديل</button></form></div>}
 </div>
}
