import {FormEvent,useEffect,useState} from 'react'
import {createUser,getUsers,resetUserPassword,updateUser} from '../data/users'
import {DataTable} from '../components/DataTable'

export function UsersPage(){
 const [data,setData]=useState<any>({users:[],branches:[]}),[error,setError]=useState(''),[msg,setMsg]=useState(''),[editing,setEditing]=useState<any|null>(null)
 const load=()=>getUsers().then(setData).catch(e=>setError(e.message||String(e)))
 useEffect(()=>{void load()},[])
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{setMsg('جاري الإنشاء…');await createUser({full_name:f.get('full_name'),email:f.get('email'),password:f.get('password'),role:f.get('role'),branch_ids:f.getAll('branch_ids')});setMsg('تم إنشاء المستخدم');(e.currentTarget as HTMLFormElement).reset();await load()}catch(x:any){setMsg(x.message)}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget);try{setMsg('جاري الحفظ…');await updateUser({user_id:editing.user_id,full_name:String(f.get('full_name')||''),role:String(f.get('role')||'branch_user'),is_active:String(f.get('is_active'))==='1',branch_ids:f.getAll('branch_ids')});const password=String(f.get('new_password')||'');if(password)await resetUserPassword(editing.user_id,password);setEditing(null);setMsg(password?'تم حفظ التعديلات وتغيير كلمة المرور':'تم حفظ التعديلات');await load()}catch(x:any){setMsg(x.message||String(x))}}
 return <div>
  {error&&<div className="error-box">{error}</div>}
  <section className="panel"><h2>إضافة مستخدم</h2><form className="user-form" onSubmit={add}><input name="full_name" placeholder="الاسم" required/><input name="email" type="email" placeholder="البريد الإلكتروني" required/><input name="password" type="password" minLength={8} placeholder="كلمة مرور مؤقتة" required/><select name="role" defaultValue="branch_user"><option value="branch_user">مستخدم فرع</option><option value="analyst">محلل</option><option value="admin">مدير</option></select><div className="checks">{data.branches?.map((b:any)=><label key={b.id}><input type="checkbox" name="branch_ids" value={b.id}/>{b.name}</label>)}</div><button className="primary">إضافة</button></form>{msg&&<p className="muted">{msg}</p>}</section>
  <DataTable title="المستخدمون" rows={data.users||[]} columns={[{key:'full_name',label:'الاسم'},{key:'email',label:'البريد'},{key:'role',label:'الدور'},{key:'is_active',label:'الحالة',render:r=>r.is_active?'نشط':'موقوف'},{key:'branch_ids',label:'الفروع',render:r=>r.role==='admin'||r.role==='analyst'?'كل الفروع':(r.branch_ids||[]).map((id:string)=>data.branches.find((b:any)=>b.id===id)?.name||'—').join('، ')},{key:'last_sign_in_at',label:'آخر دخول',render:r=>r.last_sign_in_at?new Date(r.last_sign_in_at).toLocaleString('en-GB'):'—'},{key:'created_at',label:'تاريخ الإنشاء',render:r=>r.created_at?new Date(r.created_at).toLocaleDateString('en-GB'):'—'},{key:'action',label:'إجراء',filter:false,render:r=><button className="small-btn" onClick={()=>setEditing(r)}>تعديل</button>}]}/>
  {editing&&<div className="modal-backdrop"><form className="modal-card" onSubmit={save}><div className="modal-head"><h3>تعديل المستخدم</h3><button type="button" className="small-btn" onClick={()=>setEditing(null)}>إغلاق</button></div><div className="form-grid"><label>الاسم<input name="full_name" defaultValue={editing.full_name||''} required/></label><label>البريد<input value={editing.email||''} disabled dir="ltr"/></label><label>الدور<select name="role" defaultValue={editing.role}><option value="branch_user">مستخدم فرع</option><option value="analyst">محلل</option><option value="admin">مدير</option></select></label><label>الحالة<select name="is_active" defaultValue={editing.is_active?'1':'0'}><option value="1">نشط</option><option value="0">موقوف</option></select></label><label className="full">كلمة مرور مؤقتة جديدة<input name="new_password" type="password" minLength={8} placeholder="اختياري — 8 أحرف على الأقل"/></label><div className="full"><small className="muted">اختيار الفروع يطبق على مستخدم الفرع فقط؛ المدير والمحلل يريان كل الفروع.</small></div><div className="full checks">{data.branches?.map((b:any)=><label key={b.id}><input type="checkbox" name="branch_ids" value={b.id} defaultChecked={(editing.branch_ids||[]).includes(b.id)}/>{b.name}</label>)}</div></div>{msg&&<p className="muted">{msg}</p>}<button className="primary">حفظ التعديلات</button></form></div>}
 </div>
}
